### ISSUE TITLE
macOS sierra builds of the `.app` don't work with 10.10

### ISSUE THREAD

**Issue by ghost** [minecraft-linux/osx-packaging-scripts#1]
dyld: Symbol not found: _clock_getres
  Referenced from: /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client
Process exited with unexpected exit code: 5

In the future I would like to see the program work with older OS X

**Comment by MCMrARM** [comment]
Obviously stuff built on a later release of Mac OS won't work on previous versions. This usecase scenario is not supported.

**Comment by jcfr** [comment]
Facing similar issue, I found this issue report.

This particular issue may be related to a "bug" in header provided in 10.12 SDK. See https://bugzilla.xamarin.com/show_bug.cgi?id=41786

> stuff built on a later release of Mac OS won't work on previous versions

By targeting an older macos version, it is indeed possible to build for an older macOS version. This is done in CMake setting the variable `CMAKE_OSX_DEPLOYEMENT_TARGET`
